### ISSUE TITLE
eslint-plugin-diff doesn't play nicely with the eslint-webpack-plugin

### ISSUE THREAD

**Issue by bdavies6086** [paleite/eslint-plugin-diff#10]
Hi,

This is a great plugin! However I've been having troubles integrating it with the eslint-webpack-plugin

What I've found is that the plugin intermittently works and lints line changes, however the majority of the time it won't lint anything. I've had the eslint-webpack-plugin  lintDirtyModulesOnly flag enabled if this helps replicating the issue and have been using the plugin:diff/diff config

eslint-webpack-plugin: 2.5.4
webpack: 5.15.0

Thanks!
Ben

**Comment by paleite** [comment]
Thanks for raising this issue, Ben.
I’ve never tested this with `eslint-webpack-plugin`, so this is really good to know.

Would you be able to create a minimal reproduction-repo for this, so I could inspect it the same way you do? That would be tremendously helpful in ensuring it’s working for you as expected.

Thanks again for reporting! 🙂

**Comment by paleite** [comment]
@bdavies6086 Hi!
If you get the opportunity to share a reproduction repo or some examples on this issue at any time, I’ll be more than happy to look into it. In the meantime I’ll close this issue, in the hopes that you were able to resolve the matter.

Thanks again for reporting!
