### ISSUE TITLE
Usage with vscode-eslint - file list is not updated on save

### ISSUE THREAD

**Issue by cyberbiont** [paleite/eslint-plugin-diff#17]
Right now when I use `eslint-plugin-diff`  with` dbaeumer.vscode-eslint`, the files list passed to Eslint does not update automatically.
To do this I have to manually run `'restart ESLint: restart ESLint server' `each time.
For example, I have an eslint error in some old file, that is not getting linted due to `eslint-plugin-diff`.
After I change the line, that contains error, save the file and that change is picked up by Git, I expect that `vscode-eslint` will start to give me errors, but this does not happen until I manually restart eslint server.
This kind of defeats the purpose.
Don't know if the problem is with `eslint-plugin-diff` or `vscode-eslint`
But I suspect this can be connected with git diff caching

**Comment by paleite** [comment]
Hi! Please try https://www.npmjs.com/package/eslint-plugin-diff/v/1.0.13-3 and let me know if the issue persists!

Thanks for reporting!
