### ISSUE TITLE
fatal: bad revision '"HEAD"' linux plateform

### ISSUE THREAD

**Issue by maxerbox** [paleite/eslint-plugin-diff#22]
It seems that the HEAD argument of the git diff command is a little bit too much escaped.
I get : 
```sh
command failed: git diff --diff-algorithm=histogram --diff-filter=ACM -M100% --relative --unified=0 "HEAD" -- "useFormsListCards.ts" fatal: bad revision '"HEAD"' 
```

Consider removing the double quotes

Version I'm currently using : 1.0.13
I also tested with 1.0.14. It is critical in this version

I've the same issue with the function sanitizeFilePath.

**Comment by paleite** [comment]
Thanks! looking into it

**Comment by paleite** [comment]
@maxerbox Could you see if version `1.0.15-0` fixes your issue?

**Comment by maxerbox** [comment]
Yes, it is fixed !
