### ISSUE TITLE
don't minify packages.

### ISSUE THREAD

**Issue by burtonator** [paleite/eslint-plugin-diff#33]
**Is your feature request related to a problem? Please describe.**

I'm trying to debug a problem with this plugin and hack it locally but you minify which blows symbols out of the water and makes it hard / impossible to debug.

**Describe the solution you'd like**

Don't minify. You're saving maybe 1-2k ... not worth it.

**Describe alternatives you've considered**

None... this is the only solution :)

**Additional context**

none.

**Comment by paleite** [comment]
Thanks, I've published the PR as a pre-release for now and will release stable soon: `npm i eslint-plugin-diff@2.0.2-2`
