### ISSUE TITLE
Add types in the package

### ISSUE THREAD

**Issue by mathieutu** [paleite/eslint-plugin-diff#35]
Hey, thanks for your work!

**Is your feature request related to a problem? Please describe.**
Your package is written is TS. 
The package.json had a `types` entry to `dist/index.d.ts` but this file doesn't exist.

I would be quite handy to have them to be able to import and use the methods directly.

**Describe the solution you'd like**
```diff
- "declaration": false,
+ "declaration": true, 
```
in `tsconfig.build.json`

**Describe alternatives you've considered**
🤷 
**Additional context**
Happy to do the PR.
Thanks!

**Comment by paleite** [comment]
Hi, good  idea!
Please do the PR if you have the time, otherwise I will be able to do it myself fairly soon.

Thanks for the suggestion
