### ISSUE TITLE
Help - Diff Plugin not compatible with new flat config

### ISSUE THREAD

**Issue by mlwyatt** [paleite/eslint-plugin-diff#47]
Either this plugin isn't compatible with [ESLint's flat config file](https://eslint.org/docs/latest/use/configure/configuration-files-new) yet, or I'm not setting it up quite right.

Here's a simple example:

<details>
<summary>Config</summary>

```js
import globals from 'globals';
import diff from 'eslint-plugin-diff';

export default [
  {
    ...diff.configs.diff.overrides[0],
    plugins: { diff },
    processor: diff.processors.diff,
  },
  {
    rules: {
      'no-console': ['error'],
    },
  },
];

```
</details>

```diff
console.log(1);
+console.log(2);
console.log(3);
console.log(4);
```

### Expected

```
  2:1  error  Unexpected console statement  no-console
```

### Actual

```
  1:1  error  Unexpected console statement  no-console
  2:1  error  Unexpected console statement  no-console
  3:1  error  Unexpected console statement  no-console
  4:1  error  Unexpected console statement  no-console
```

Any help would be appreciated.
Thanks in advance

**Comment by paleite** [comment]
Ah, that's interesting. Great find! Do you have a reproduction repository i could check?

**Comment by mlwyatt** [comment]
Unfortunately, I don't. I was migrating a couple of my work projects, one of which is written in TS, to the flat config but then came across [this](https://github.com/typescript-eslint/typescript-eslint/issues/5938#issuecomment-1316416378) saying the TS plugin won't be updated until the flat config is almost finished. Once I found out that, I just dropped it and moved on

**Comment by Lucasgb7** [comment]
Are there any updates about ESLint's flat config support?

**Comment by aloner-pro** [comment]
```
const prettier = require('eslint-plugin-prettier');

module.exports = [
  {
    files: ['**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx'],
    ignores: ['eslint.config.js'],
    languageOptions: {
      parser: require('@typescript-eslint/parser'),
      ecmaVersion: 2021,
      sourceType: 'module',
    },
    plugins: {
      prettier,
    },
    rules: {
      'prettier/prettier': 'error',
      'semi': ['warn', 'always'],
    },
  },
];
```
here is my eslint.config.js can anybody explain how can I integrate `eslint-plugin-diff` to check linting issues only on modified or newly added lines?
